name: action_indicators
description: Indicators of actions around any widgets
version: 0.0.2
repository: https://github.com/jovermars/action-indicators

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: